config/routes.rb
AmazonApp::Application.routes.draw do

  get "store", :controller => "items", :action => "index", :as => :items
  post "store", :controller => "items", :action => "create"
  
  get "store/new", :controller => "items", :action => "new", :as => :new_item
  
  get "store/:id", :controller => "items", :action => "show", :as => :item
  put "store/:id", :controller => "items", :action => "update"
  delete "store/:id", :controller => "items", :action => "destroy"
 
  get "store/:id/edit", :controller => "items", :action => "edit", :as => :edit_item
  
  
  get "cart", :controller => "carts", :action => "index", :as => :carts
  put "cart/:id", :controller => "carts", :action => "update", :as => :cart

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :name, :price, :quantity
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @items = Item.all
    @items.each do |item|
      if Cart.find_by_name(item.name).nil?  # --> If item is available, but not in cart, add to cart
        c = Cart.new
        c.name = item.name
        c.price = item.price
        c.quantity = 0
        c.save
      else
        c = Cart.find_by_name(item.name)  #--> If item is available and in cart, make sure price is up to date
        c.price = item.price
        c.save
      end
    end
    @carts = Cart.all
    @carts.each do |cart|
      if Item.find_by_name(cart.name).nil?  # --> If item is in cart, but unavailable, remove from cart
        c = Cart.find_by_name(cart.name)
        c.destroy
      end
    end   # --> ^ Makes sure that shopping cart is up to date with available items
    @total = 0
    @carts.each do |cart|
      @total += (cart.price * cart.quantity)
    end
    @carts = Cart.all    
  end
  
  def update
    @items = Item.all
    @items.each do |item|
      if Cart.find_by_name(item.name).nil?  # --> If item is available, but not in cart, add to cart
        c = Cart.new
        c.name = item.name
        c.price = item.price
        c.quantity = 0
        c.save
      else
        c = Cart.find_by_name(item.name)  #--> If item is available and in cart, make sure price is up to date
        c.price = item.price
        c.save
      end
    end   #--> Makes sure all available items are in cart before making adjustments to quantities (if item has just been created 
          #    before "Add to Cart" request, item must be first added to Cart before quantity can be changed)
          
    if params[:id].to_i == 0  # --> If params[:id] delivers a string (send is from "Add to Cart" not "Update Quantity")
      c = Cart.find_by_name(params[:id])
      c.quantity += 1
      c.save
    else  # --> Else params[:id] is an integer (send is from "Update Quantity" not "Add to Cart")
      c = Cart.find_by_id(params[:id])
      c.quantity = params[:quantity]
      c.save
    end
    redirect_to carts_url    
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end
  
  def create
    i = Item.new
    i.name = params[:item][:name]
    i.price = params[:item][:price]
    i.save
    redirect_to items_url
  end
  
  def new
    @item = Item.new
  end
  
  def show
    @item = Item.find_by_id(params[:id])
  end
  
  def update
    i = Item.find_by_id(params[:id])
    i.name = params[:item][:name]
    i.price = params[:item][:price]
    i.save
    redirect_to items_url
  end
  
  def destroy
    i = Item.find_by_id(params[:id])
    i.destroy
    redirect_to items_url
  end
  
  def edit
    @item = Item.find_by_id(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/index.html.erb
<h1>Your Shopping Cart</h1>
<ul>
  <% @carts.each do |cart|%>
    <li><%= cart.name %> | 
      $<%= cart.price %>
      <%= form_tag(cart_url(cart.id), :method => :put) do %> <!-- Sends cart.id instead of cart.name to distinguish "Update Quantity" request from "Add to Cart": see update method in carts_controller -->
        <%= text_field_tag :quantity, cart.quantity %> 
        <%= submit_tag "Update quantity"%>
      <% end %>
    </li>
  <% end %>
</ul>
<p>Total = $<%= @total%></p>
<br>
<%= link_to "Return", items_url %>

app/views/items/_form.html.erb
<%= form_for(@item) do |form| %>

  <div>
  <%= form.label :name, "Name of Item:" %>
  <%= form.text_field :name %>
  </div>
  
  <div>
  <%= form.label :price, "Price:" %>
  <%= form.text_field :price %>
  </div>
  
  <%= form.submit %>
<% end %>

app/views/items/edit.html.erb
<h1><%=@item.name %></h1>

<%= render "form" %>
<br>
<%= link_to "Return", items_url %>

app/views/items/index.html.erb
<h1>Welcome To Amazon</h1>
<br>
<ul>
  <li>Items</li>
    <ul>
      <% @items.each do |item| %>
        <li><%= link_to "#{item.name}", item_url(item.id) %> | $<%= item.price %> | 
          <%= link_to "Edit", edit_item_url(item.id) %> | 
          <%= link_to "Delete Item", item_url(item.id), :method => :delete, :confirm => "Are you sure?" %> | 
          <%= link_to "Add to Cart",  cart_url(item.name), :method => :put %> <!-- Sending @item.name instead of @item.id distinguishes "Add to Cart" request from "Update Quantity": See update method in cart_controller -->
        </li>
      <% end %>
    </ul>
</ul>
<%= link_to "Add a New Item", new_item_url %>

app/views/items/new.html.erb
<%= render "form"%>
<br>
<%= link_to "Return", items_url%>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<h2>Price: <%= @item.price %></h2>
<p><%= link_to "Edit Item", edit_item_url(@item.id) %></p>
<p><%= link_to "Delete Item", item_url(@item.id), :method => :delete, :confirm => "Are you certain?" %></p>
<p><%= link_to "Add to Cart", cart_url(@item.name), :method => :put %></p>  <!-- Sending @item.name instead of @item.id distinguishes "Add to Cart" request from "Update Quantity": See update method in cart_controller -->
<br>
<%= link_to "Return", items_url%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmazonApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>